name: ci-hf-distilbert

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - "src/**"
      - ".github/workflows/**"
      - "requirements.txt"

env:
  HF_USERNAME: gkovacsvelasco
  HF_MODEL_ID: gkovacsvelasco/distilbert-qa-qasports
  DATA_DIR: data/processed/qasports_soccer_basketball
  MAX_PER_SPORT: "5000"   # ajuste p/ +rápido ou +lento
  EPOCHS: "1"
  TRAIN_BS: "8"
  EVAL_BS: "8"
  GRAD_ACCUM: "2"
  LR: "3e-5"
  HUGGINGFACE_HUB_TOKEN: ${{ secrets.HUGGINGFACE_TOKEN }}

jobs:
  prepare_data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python + pip cache
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: |
            requirements.txt

      - name: Cache Hugging Face ~/.cache/huggingface
        uses: actions/cache@v4
        with:
          path: ~/.cache/huggingface
          key: hf-${{ runner.os }}-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            hf-${{ runner.os }}-

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Prepare dataset (subset soccer+basketball)
        run: |
          python src/data/prepare_qasports.py \
            --dataset PedroCJardim/QASports \
            --splits train,validation \
            --max-per-sport ${MAX_PER_SPORT} \
            --out ${DATA_DIR}
          ls -R ${DATA_DIR}

      - name: Upload dataset artifact
        uses: actions/upload-artifact@v4
        with:
          name: qasports_subset
          path: ${{ env.DATA_DIR }}

  train_and_push:
    needs: prepare_data
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python + pip cache
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: |
            requirements.txt

      - name: Cache Hugging Face ~/.cache/huggingface
        uses: actions/cache@v4
        with:
          path: ~/.cache/huggingface
          key: hf-${{ runner.os }}-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            hf-${{ runner.os }}-

      - name: Download dataset artifact
        uses: actions/download-artifact@v4
        with:
          name: qasports_subset
          path: ${{ env.DATA_DIR }}

      - name: Install deps + torch cpu
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install torch --index-url https://download.pytorch.org/whl/cpu

      - name: Train DistilBERT QA (CPU, subset)
        run: |
          python src/train_distilbert_qa.py \
            --data_dir ${DATA_DIR} \
            --base_model distilbert-base-uncased \
            --output_dir outputs/distilbert_qa \
            --epochs ${EPOCHS} \
            --train_batch ${TRAIN_BS} \
            --eval_batch ${EVAL_BS} \
            --grad_accum ${GRAD_ACCUM} \
            --lr ${LR} \
            --push_to_hub \
            --hub_model_id ${HF_MODEL_ID}

      - name: Upload model artifact
        uses: actions/upload-artifact@v4
        with:
          name: distilbert_qa_outputs
          path: outputs/distilbert_qa

      - name: Upload predictions & metrics
        uses: actions/upload-artifact@v4
        with:
          name: distilbert_reports
          path: |
            outputs/distilbert_qa/sample_predictions.json
            outputs/distilbert_qa/metrics_summary.json

  deploy_space:
    needs: train_and_push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python + pip cache
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: |
            requirements.txt

      - name: Install hub client
        run: |
          python -m pip install --upgrade pip
          pip install huggingface_hub>=0.24.5

      - name: Create/Update Space (Gradio)
        env:
          HF_TOKEN: ${{ env.HUGGINGFACE_HUB_TOKEN }}
          HF_SPACE_ID: gkovacsvelasco/sports-qa-demo
          HF_MODEL_ID: ${{ env.HF_MODEL_ID }}
        run: |
          python spaces/deploy_space.py
